### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by revoluta** [deiger/AirCon#106]
Hello, i have a problem to connect to mosquito broker, i use home assistant, i have AEH-W4E1 wifi module.
i have try it very much, but i not find a solution.

Would you like so kind to help me, thanks.

Mosquito config:
-------------------
logins:
  - username: mqtt
    password: *******
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
anonymous: false

HiSense Air Conditioners config
-----------------------------------
log_level: INFO
mqtt_host: 192.168.1.2
mqtt_user: mqtt
mqtt_pass: *****
port: 1883
app:
  - username: ********@gmail.com
    password: *********
    code: hisense-eu

Log error
----------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/aircon/__main__.py", line 304, in <module>
    asyncio.run(run(parsed_args))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/app/aircon/__main__.py", line 253, in run
    query_status_worker(devices), notifier.start(session))
  File "/app/aircon/__main__.py", line 153, in setup_and_run_http_server
    await site.start()
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.7.4-py3.7-linux-armv7l.egg/aiohttp/web_runner.py", line 128, in start
    reuse_port=self._reuse_port,
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1389, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('::', 1883, 0, 0): address already in use

**Comment by deiger** [comment]
`1883` is the port used by the MQTT server (the default one, if you would like to use a different one, `mqtt_port` can be set to it).
The port set by the `port` option is used for the AC server, as the protocol requires the AC to open connections against it. Since your MQTT server and the AC server are running on the same host, the port is already in use by the former. Please change the `port` option to a different value.

**Comment by Pirol62** [comment]
I set the port to 8888. That worked.
