### ISSUE TITLE
Error when running server

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [deiger/AirCon#126]
I get this error `Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\python\lib\site-packages\aircon-0.3.9-py3.9.egg\aircon\__main__.py", line 304, in <module>
  File "C:\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\python\lib\site-packages\aircon-0.3.9-py3.9.egg\aircon\__main__.py", line 169, in run
  File "C:\python\lib\site-packages\aircon-0.3.9-py3.9.egg\aircon\aircon.py", line 68, in create
KeyError: 'model'` when i'm running `python -m aircon run --port 8888 --config config.json --mqtt_host localhost`. I did everything right, what could be wrong?

**Comment by hzpz** [comment]
Did you run the discovery command? Is there a `config.json` in the directory you're running the command from? And if so, what's its content?

Try deleting `config.json` (if it exists) and rerunning the discovery command.
