### ISSUE TITLE
Connection refused when trying to run hisense.py

### ISSUE THREAD

**Issue by Stego2310** [deiger/AirCon#13]
Hi, I very much appreciate your work and hope to be able to implement it to avoid using two apps for my three devices (one has unfortunately an AEH-W4B1 and both others the W4E1 module so that I need to use two apps...).

Unfortunately, I'm not able to run the server properly and have no clue what else to do - I've set up various VMs with Ubuntu and Debian, also a Raspberry pi with Raspbian, but all attempts end up with the same result. I am able to generate all the config.json files for my three modules, but when starting the hisense.py server I am presented with the following:

`./hisense.py --port 8888 --ip 192.168.193.73 --config configWohnzimmer.json --mqtt_host localhost
Traceback (most recent call last):
  File "./hisense.py", line 746, in <module>
    _mqtt_client.connect(_parsed_args.mqtt_host, _parsed_args.mqtt_port)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused`

Every help on this would be much appreciated and thanks again for your work!
If you need additional infos, just let me know.

**Comment by Stego2310** [comment]
Figured out that there needs to be a MQTT server running but I've initially thought it would be started automatically via the hisense.py script - I've added now a MQTT server to one of the machines and the server was finally able to connect.
