### ISSUE TITLE
ConnectionRefusedError while starting the server

### ISSUE THREAD

**Issue by thizmo** [deiger/AirCon#132]
Dear all, 

i installed the software just fine.
Used the hisense-eu app and also got the configuration for all the devices.
I also can remotely adminstrate the devices within the app.

Yet while running the server, i got the following error messages below.
My OS is Ubuntu 20.04 LTS with python 3.8.
Tried it on Intel and on Raspberry PI. The same results.

This is a nmap (-PN) for of one of my devices:

 Host is up (0.013s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
80/tcp open  http
MAC Address: CA:2C:4F:95:83:5A (Unknown)

That is why i used port 80 here.
Also with default of 8888 the output is the same.

Hopefully anyone has any ideas?

```
python3 -m aircon --log_level DEBUG run -p 80 --config config_firstdevice.json --type ac --mqtt_host localhost  
                   1 ↵
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/username/Klima/AirCon/aircon/__main__.py", line 304, in <module>
    asyncio.run(run(parsed_args))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/username/Klima/AirCon/aircon/__main__.py", line 189, in run
    mqtt_client.connect(parsed_args.mqtt_host, parsed_args.mqtt_port)
  File "/usr/local/lib/python3.8/dist-packages/paho_mqtt-1.5.0-py3.8.egg/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/dist-packages/paho_mqtt-1.5.0-py3.8.egg/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.8/dist-packages/paho_mqtt-1.5.0-py3.8.egg/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

Thx in advance

**Comment by thizmo** [comment]
So after a few days of experimenting with different setups, the problem seems to be a missing mqtt server while trying to start it manually.  When running all of it on top of homeassistent, and figuring out in this documentation that also an mqtt server has to be running seperatly (and easily) on homeassistent, also figuring out how homeassistent and mqtt discovery works, i now have controll over my AC from the lovelace UI. Still i have no clue on how to control the devices (and more features then actually in the UI) and even more to make them smart. ;-) Yet with a few more days i will eventually got there.

Thx for the great software!

**Comment by roxyamaha** [comment]
@thizmo how did you solve this?
I'm having same issue. Running everything in containers, do I need run mqtt server as separate container?
What then when I run mqtt, how to connect with AC?

**Comment by thizmo** [comment]
Hi @roxyamaha,

i use homeassistant. In homeassistant i just added the MQTT-service (installable) and then startet it. Then configure the default as described in the documentation part. When installed also Aircon, you have to configure the mqtt_part inside the configuration of aircon.

Below you can see my homeassistant "add-on" Store for the two related parts.
![2022-05-05_15h10_35](https://user-images.githubusercontent.com/26714256/166930510-d211ad44-65e1-4d95-bf3e-6f21161cd7d8.png)

So to anwser your question, yes. Without an MQTT-service (could also be a container) it won't work. And aircon has to communicate with the MQTT-container in the end.

Hope it helps.
.
