### ISSUE TITLE
Mqtt fail

### ISSUE THREAD

**Issue by kisjeth** [deiger/AirCon#136]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/aircon/__main__.py", line 304, in <module>
    asyncio.run(run(parsed_args))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/app/aircon/__main__.py", line 253, in run
    query_status_worker(devices), notifier.start(session))
  File "/app/aircon/__main__.py", line 153, in setup_and_run_http_server
    await site.start()
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.7.4-py3.7-linux-aarch64.egg/aiohttp/web_runner.py", line 128, in start
    reuse_port=self._reuse_port,
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1389, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('::', 1883, 0, 0): address already in use`

What's wrong? in the list of problems already solved I saw a post similar to mine in which it was recommended to remove the server port entry but if I try to remove that entry or leave it empty it does not allow me to save.

log_level: INFO
mqtt_host: 192.168.x.x
mqtt_user: mqtt username
mqtt_pass: mqtt psw
port: 1883
app:
  - username: xxxxxxx@yyy.com
    password: asdasdasd
    code: hisense-eu

**Comment by kisjeth** [comment]
I found the solution in one post. I change the port from 1883 to 8888.
