### ISSUE TITLE
HiSense - KeyError: 'model'

### ISSUE THREAD

**Issue by saragrigolin** [deiger/AirCon#198]
Hi everyone,
I have an Hisense  Air Conditioner with AEH-W4E1 wi-fi module.
Everything worked correctly for a few months until a week ago the air conditioner became unavailable with this error:
`D0827 15:38:02.102  selector_events.py:58] Using selector: EpollSelector`
`Traceback (most recent call last):`
 ` File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main`
   ` "__main__", mod_spec)`
  `File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code`
    `exec(code, run_globals)`
 ` File "/app/aircon/__main__.py", line 304, in <module>`
   ` asyncio.run(run(parsed_args))`
`  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run`
   ` return loop.run_until_complete(main)`
 ` File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete`
  `  return future.result()`
 ` File "/app/aircon/__main__.py", line 169, in run`
    `device = Device.create(config, notifier.notify)`
 ` File "/app/aircon/aircon.py", line 68, in create`
   ` model = config['model']`
`KeyError: 'model'`

I didn't change anything and I tried to reinstall AirCon with no success. What can I do?
Thank you

**Comment by dvdavide** [comment]
Does the AC works with the mobile app? Does it have a fixed IP address?

Delete the config_[ac_name].json from the configuration folder; while you are there also double check that the options.json has not been accidentally modified. Then restart the AirCon container and see if it works.

**Comment by saragrigolin** [comment]
> Does the AC works with the mobile app? Does it have a fixed IP address?
> 
> Delete the config_[ac_name].json from the configuration folder; while you are there also double check that the options.json has not been accidentally modified. Then restart the AirCon container and see if it works.

Hi, sorry for the late reply.
Yes, the AC works with the mobile app, and has a fixed IP address. 

I removed the config_[ac_name].json and I don't have any options.json file (maybe cause I configured the addon from its UI?). I tried to uninstall and reinstall AirCon and now when I configure it I have this error:
`E0915 19:14:00.916  discovery.py:43] Failed to login to Hisense server:`
`Status 401: 'Unauthorized'`

Someone had the same issue (#165 #156 #99) and I tried everything suggested with no success, including creating a new account on HiSense app.

Here's my configuration (I'm sure that mqtt and Hisense app credentials are correct). The code is hisense-eu cause I use HiSmart Life app.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/56165909/190471135-02b12035-8093-4baa-8470-57578a80e201.png">
