### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by crispy78** [deiger/AirCon#218]
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:09:17 PM (4 occurrences)
Last logged: 8:11:48 PM

[140075944547072] Error updating HiSense Air Conditioners: Can't install deiger/aircon:0.3.11: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.3.11&fromImage=deiger%2Faircon&platform=linux%2Famd64: Not Found ("manifest for deiger/aircon:0.3.11 not found: manifest unknown: manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install deiger/aircon:0.3.11: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.3.11&fromImage=deiger%2Faircon&platform=linux%2Famd64: Not Found ("manifest for deiger/aircon:0.3.11 not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating HiSense Air Conditioners: Can't install deiger/aircon:0.3.11: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.3.11&fromImage=deiger%2Faircon&platform=linux%2Famd64: Not Found ("manifest for deiger/aircon:0.3.11 not found: manifest unknown: manifest unknown")

**Comment by saveriospeziali** [comment]
Same for me

**Comment by crispy78** [comment]
I've uninstalled the addon in Home Assistant, restarted HA, checked for updates in the Add-on section and tried to install it. It wouldn't install and this is the log from that error.

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:125
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 9:25:31 PM (3 occurrences)
Last logged: 9:39:01 PM

Failed to to call /addons/c34eddb3_hisense_ac/install - Can't install deiger/aircon:0.3.11: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.3.11&fromImage=deiger%2Faircon&platform=linux%2Famd64: Not Found ("manifest for deiger/aircon:0.3.11 not found: manifest unknown: manifest unknown")

**Comment by crispy78** [comment]
BTW I'm running HA as a Virtual Machine on a Synology NAS, my current installation is up-to-date:
Home Assistant 2023.3.3
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.0 - latest

**Comment by pbvdven** [comment]
same here.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:03:50 (5 occurrences)
Last logged: 22:05:09

[140543280823216] Error updating HiSense Air Conditioners: Can't install deiger/aircon:0.3.11: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=0.3.11&fromImage=deiger%2Faircon&platform=linux%2Famd64: Not Found ("manifest for deiger/aircon:0.3.11 not found: manifest unknown: manifest unknown")
[140540913785760] Error updating HiSense Air Conditioners: Can't install deiger/aircon:0.3.11: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=0.3.11&fromImage=deiger%2Faircon&platform=linux%2Famd64: Not Found ("manifest for deiger/aircon:0.3.11 not found: manifest unknown: manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install deiger/aircon:0.3.11: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=0.3.11&fromImage=deiger%2Faircon&platform=linux%2Famd64: Not Found ("manifest for deiger/aircon:0.3.11 not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating HiSense Air Conditioners: Can't install deiger/aircon:0.3.11: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=0.3.11&fromImage=deiger%2Faircon&platform=linux%2Famd64: Not Found ("manifest for deiger/aircon:0.3.11 not found: manifest unknown: manifest unknown")

**Comment by deiger** [comment]
Sorry about that. I was trying to build a new version, and docker build misbehaved.
This should be fixed now.
