### ISSUE TITLE
'NoneType' object has no attribute 'loop'

### ISSUE THREAD

**Issue by kekkodance** [deiger/AirCon#234]
When running AirCon both as a docker container and from python itself, i always get an error.
```

sudo python3 -m aircon run --port 8888 --config config_splitairconditioner.json 
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kekko/AirCon/aircon/__main__.py", line 304, in <module>
    asyncio.run(run(parsed_args))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/kekko/AirCon/aircon/__main__.py", line 252, in run
    await asyncio.gather(mqtt_loop(mqtt_client), setup_and_run_http_server(parsed_args, devices),
  File "/home/kekko/AirCon/aircon/__main__.py", line 163, in mqtt_loop
    mqtt_client.loop()
AttributeError: 'NoneType' object has no attribute 'loop'
```
happens with and without sudo

**Comment by miguellobato84** [comment]
you need to set up a mqtt server

**Comment by kekkodance** [comment]
i have one setup using mosquitto on the same machine on localhost and it's in the config yet it still does that @miguellobato84

**Comment by miguellobato84** [comment]
but you need to specify it as an argument
