### ISSUE TITLE
Error in HomeAssistant

### ISSUE THREAD

**Issue by nenone78** [deiger/AirCon#236]
I  have two HiSense AC prefectly used by Hi Smart AC App ("oem-eu" code). I cannot understand the maning of
"
Multiple Air Conditioners
In order to use with multiple Air Conditioners, simply add multiple --config params. MQTT topic will contain your topic defined by flag --mqtt_topic (hisense_ac by default) and device MAC address (for uniqueness).
"
So I cannot configure the TWO AC, and the two local IP (192.168.1.51 and 192.168.1.52). So it gives this error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/app/aircon/__main__.py", line 304, in <module>
>     asyncio.run(run(parsed_args))
>   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/app/aircon/__main__.py", line 252, in run
>     await asyncio.gather(mqtt_loop(mqtt_client), setup_and_run_http_server(parsed_args, devices),
>   File "/app/aircon/__main__.py", line 157, in setup_and_run_http_server
>     await site.start()
>   File "/usr/local/lib/python3.10/site-packages/aiohttp-3.7.4-py3.10-linux-aarch64.egg/aiohttp/web_runner.py", line 121, in start
>     self._server = await loop.create_server(
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1519, in create_server
>     raise OSError(err.errno, 'error while attempting '
> OSError: [Errno 98] error while attempting to bind on address ('::', 1883, 0, 0): address already in use
> 

Any help is appreciated!

**Comment by mikojacko** [comment]
What type of implementation are you using? The best is to add the addon-repository and install https://github.com/deiger/AirCon plus MQTT Broker add-on and follow the instruction of the addons itselfs. You have to configure both  services.

**Comment by tremendo88** [comment]
you need change the port, Aircon and mqtt now have a same port, change 1883 to 8888

**Comment by legantois** [comment]
@deiger 
Hello Dror
how can we helpin this ?

**Comment by nenone78** [comment]
> What type of implementation are you using? The best is to add the addon-repository and install https://github.com/deiger/AirCon plus MQTT Broker add-on and follow the instruction of the addons itselfs. You have to configure both services.

i use it as addonsin HA

**Comment by nenone78** [comment]
i just update to last version 0.3.16, but the add on doesn't work and i still can't understand hoe i can configure two AC: Now the log reports:

"Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/aircon/__main__.py", line 303, in <module>
    asyncio.run(run(parsed_args))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/aircon/__main__.py", line 251, in run
    await asyncio.gather(mqtt_loop(mqtt_client), setup_and_run_http_server(parsed_args, devices),
  File "/app/aircon/__main__.py", line 157, in setup_and_run_http_server
    await site.start()
  File "/usr/local/lib/python3.10/site-packages/aiohttp-3.8.5-py3.10-linux-aarch64.egg/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1519, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('::', 1883, 0, 0): address already in use
"

**Comment by deiger** [comment]
Could you please detail here your config in HA?
Go to the Configuration page of the add-on, switch to 'Edit in YAML', and copy the data.

**Comment by nenone78** [comment]
log_level: INFO
mqtt_host: localhost
mqtt_user: NeNo
mqtt_pass: XXXXXX
port: 1883
app:
  - username: stefano.ioppi@gmail.com
    password: XXXXXXXX
    code: oem-eu
local_ip: 192.168.1.51

**Comment by nenone78** [comment]
the error after upgrading to 0.3.17 is 
E0807 13:09:21.218  notifier.py:121] Failed to connect to 192.168.1.51, maybe it is offline?
E0807 13:09:29.230  notifier.py:121] Failed to connect to 192.168.1.51, maybe it is offline?
E0807 15:55:41.214  notifier.py:121] Failed to connect to 192.168.1.52, maybe it is offline?
E0807 15:55:49.226  notifier.py:121] Failed to connect to 192.168.1.52, maybe it is offline?

**Comment by snoopy12345** [comment]
E0808 14:26:30.867  notifier.py:121] Failed to connect to 192.168.178.38, maybe it is offline?

Same bug here, not quite sure it is related to the 0.3.17 so far

Appeared a few days ago

**Comment by PJDamen** [comment]
Starting the original app on your phone and then starting the Deiger add-on seems to temporarily fix this issue until the next start.
