### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by sapanica** [deiger/AirCon#274]
Hi there,

After following all the instructions, your HA assistant add-on told me it made connection with my hi sense ac, looking at the logs.

But a few moments later the log shows an error.

Do you know whats wrong with it?

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/aircon/__main__.py", line 303, in <module>
    asyncio.run(run(parsed_args))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/aircon/__main__.py", line 193, in run
    mqtt_client.connect(parsed_args.mqtt_host, parsed_args.mqtt_port)
  File "/usr/local/lib/python3.10/site-packages/paho_mqtt-1.6.1-py3.10.egg/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho_mqtt-1.6.1-py3.10.egg/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.10/site-packages/paho_mqtt-1.6.1-py3.10.egg/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

log_level: INFO
mqtt_host: "192.168.178.212 "
mqtt_port: 1883
mqtt_user: homeassistant
mqtt_pass: xxxxxxx
port: 1883
app:
  - username: xxxxxxxx@gmail.com
    password: xxxxxxxxxx
    code: hisense-eu
local_ip: "192.168.178.212 "

Any help is welcome!

**Comment by kevtuning** [comment]
Oh ... I get the same error from tonight...
