### ISSUE TITLE
Fan only not working

### ISSUE THREAD

**Issue by tdigu** [deiger/AirCon#276]
Firstly, i am grateful for this code, it gives a great way to control my mini split systems without added hardware or complexity to control.
The only feature that does not work for both of my mini split systems is the fan only mode.
This is some of the config:
"app": "fglair-us", "model": "AP-WA1E", "sw_version": "bc 2.6.17-fgl2 06/29/20 09:03:57 ID jre/mfg/2dfbf5d", "dsn": "AC000W000472697", "temp_type": "C", 
 "app": "fglair-us", "model": "AP-WB1E", "sw_version": "bc 2.6.17-fgl2 06/29/20 09:03:57 ID jre/mfg/2dfbf5d", "dsn": "AC000W002915637", "temp_type": "C", 

Thank you.

**Comment by satarex** [comment]
I have the same issue, 
the problem is that the application sends in configuration that it supports FAN_ONLY 
From homeassistant/climate/REDACTED/hvac/config : 
```
modes:
  - 'off'
  - fan_only
  - heat
  - cool
  - dry
  - auto
```
But it expects FAN. 
See the logs: 
```
mqtt_client.py:55] Failed to parse value FAN_ONLY for property operation_mode
Traceback (most recent call last):
  File "/app/aircon/mqtt_client.py", line 53, in mqtt_on_message
    chosen_device.queue_command(prop_name, payload.upper())
  File "/app/aircon/aircon.py", line 159, in queue_command
    data_value = data_type[value]
  File "/usr/local/lib/python3.10/enum.py", line 440, in __getitem__
    return cls._member_map_[name]
```

**Comment by DeltaNu1142** [comment]
I also have this issue. I can't turn on the fan from HA because "fan" is not the correct command.

**Comment by Cook23** [comment]
Do you find workaround for this issue ?

**Comment by DeltaNu1142** [comment]
I have found no workaround for this issue.
