### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by GZ-3** [deiger/AirCon#283]
The integration suddenly stopped working. I tried restarting the addon, rebooting home assistant. It works fine from the remote and frome the HiSmart Life app.
The addon provides the following error:
E0630 20:05:03.992  web_protocol.py:403] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp-3.8.5-py3.10-linux-x86_64.egg/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp-3.8.5-py3.10-linux-x86_64.egg/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/app/aircon/query_handlers.py", line 42, in key_exchange_handler
    updated_keys = self._devices_map[request.remote].update_key(key)
KeyError: '10.0.3.0'
I0630 20:05:03.992  web_log.py:206] 10.0.3.0 [30/Jun/2024:17:05:03 +0000] "POST /local_lan/key_exchange.json HTTP/1.1" 500 245 "-" "-"

**Comment by GZ-3** [comment]
It suddenly started working again... without me doing anything

**Comment by GZ-3** [comment]
Same problem. After a power outage last week it stopped working for good.
