### ISSUE TITLE
Error on starting add-on

### ISSUE THREAD

**Issue by PeterH63** [deiger/AirCon#300]
Hello, i get the following error when starting the add-on.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/aircon/__main__.py", line 303, in <module>
    asyncio.run(run(parsed_args))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/aircon/__main__.py", line 193, in run
    mqtt_client.connect(parsed_args.mqtt_host, parsed_args.mqtt_port)
  File "/usr/local/lib/python3.10/site-packages/paho_mqtt-1.6.1-py3.10.egg/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho_mqtt-1.6.1-py3.10.egg/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.10/site-packages/paho_mqtt-1.6.1-py3.10.egg/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

My configuration looks like that.

log_level: INFO
mqtt_host: core-mosquitto
mqtt_port: 8888
mqtt_user: mqtt-user
mqtt_pass: xxxxxxxx
port: 8123
app:
  - username: xxxxxxxx@t-online.de
    password: xxxxxxxx
    code: oem-eu

Does somebody have an idea.
Thanks for any help.

**Comment by kassyo87** [comment]
i'm running mosquito broker with default mqtt port and port 80, and it works. maybe try that.

**Comment by cvladan** [comment]
If the add-on setup is causing issues, there's an alternative: I made a fork that works as a proper HACS integration for Home Assistant — no add-on configuration, no MQTT, no Docker. Just add it as a custom repository in HACS.

https://github.com/cvladan/hassio-hacs-hisense-aircon
