### ISSUE TITLE
Values for t_temp, t_temptype and others need to be derrived from t_control_value as they are not reported on by some models

### ISSUE THREAD

**Issue by piejanssens** [deiger/AirCon#36]
t_temptype: FAHRENHEIT --> strange as display shows celcius values?
f_temp_in: shows celcius  --> OK
f_temp: shows fahrenheit value '81' , which corresponds to '27' degrees celcius. The actual setting, reported correctly through the HiSmart Life app shows '23' degrees celcius. --> PROBLEM

Probably related to https://github.com/deiger/AirCon/issues/26, but that thread seems to have got a life on its own.

I can see that f_temp_in changes to '173' (yes 1-7-3, seems a bit hot) if I use the app to disable "celcius" (and use "fahrenheit").
t_temptype remains unchanged.

BTW: I'm using AEH-W4E1.

**Comment by piejanssens** [comment]
So, 81 seems to be the default. Question is, why default?
`https://github.com/deiger/AirCon/blob/master/hisense.py#L310`

**Comment by piejanssens** [comment]
f_votage instead of f_voltage... Where is that coming from?!

```
Aug 11 20:42:33 Pieters-MacBook-Pro E0811 20: 42:33.420  hisense.py:679] Failed to handle {'seq_no': 832, 'data': {'name': 'f_votage', 'value': 230}}
	Traceback (most recent call last):
	  File "hisense.py", line 675, in property_update_handler
	    data_type = _data.properties.get_type(name)
	  File "hisense.py", line 246, in get_type
	    return cls.__dataclass_fields__[attr].type
	KeyError: 'f_votage'
```

**Comment by piejanssens** [comment]
Could it be that for the newer models the values of t_temp, t_temptype and others need to be derrived from the t_control-value?
