### ISSUE TITLE
When running multiple ACs and one host is down, other ACs are not controllable

### ISSUE THREAD

**Issue by rotem925** [deiger/AirCon#60]
Hi @deiger 
The log is full of these entries, I guess one of my ACs went down, the log appears every second or so.
But then all the ACs are not controllable through HA. Maybe the whole server does not accept any command for being too busy.
I guess in this case MQTT should report them as unavailable.

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rotem/Development/aircon/AirCon/aircon/notifier.py", line 85, in start
    await self._perform_request(session, entry)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.2.0-py3.7.egg/tenacity/_asyncio.py", line 43, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.2.0-py3.7.egg/tenacity/__init__.py", line 356, in iter
    return fut.result()
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.2.0-py3.7.egg/tenacity/_asyncio.py", line 46, in call
    result = await fn(*args, **kwargs)
  File "/Users/rotem/Development/aircon/AirCon/aircon/notifier.py", line 112, in _perform_request
    async with session.request(method, url, json=self._json, headers=config.headers) as resp:
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.252:80 ssl:default [Host is down]
E0109 09:54:24.888  notifier.py:88] [KeepAlive] Failed to send local_reg keep alive to the AC.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 962, in create_connection
    raise exceptions[0]
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 949, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 473, in sock_connect
    return await fut
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 478, in _sock_connect
    sock.connect(address)
OSError: [Errno 64] Host is down

```

**Comment by rotem925** [comment]
@deiger Well done on the availability!
I can see in MQTT explorer that you hit the availability topic for each keep-alive check..
I would check if it changed from the last report (default to offline on startup) to not hummer the MQTT broker too much..
I would actually do it elsewhere if this happens for other topics.
What do you think?

**Comment by deiger** [comment]
The trick I used here is that (thankfully) availability is a list in MQTT discovery. So there is the general availability (that changes to offline as a last will when the process is taken down), on top of the specific one for each A/C. The way this should (theoretically) work is that it takes the last update from both topics.
