### ISSUE TITLE
Error while running service

### ISSUE THREAD

**Issue by dovrose** [deiger/AirCon#62]
Hi,

I noticed an error after 10 min (with the new update to the folder opt) with the service:

* hisense.service - Hisense A/C server
     Loaded: loaded (/lib/systemd/system/hisense.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-01-09 19:05:15 UTC; 10min ago
   Main PID: 3269 (python3)
      Tasks: 1 (limit: 9251)
     Memory: 23.7M
     CGroup: /system.slice/hisense.service
             `-3269 /usr/bin/python3 -m aircon run --port 8888 --type ac --config config_yahavnitzan.json --type ac --config config_office.json --type ac --config config_s>

Jan 09 19:05:15 AvirconV2 systemd[1]: Started Hisense A/C server.
Jan 09 19:13:47 AvirconV2 python3[3269]: E0109 19:13:47.169  notifier.py:88] [KeepAlive] Failed to send local_reg keep alive to the AC.
                                         Traceback (most recent call last):
                                           File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.6.2-py3.8.egg/aiohttp/client.py", line 480, in _request
                                             conn = await self._connector.connect(
                                           File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.6.2-py3.8.egg/aiohttp/connector.py", line 523, in connect
                                             proto = await self._create_connection(req, traces, timeout)
                                           File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.6.2-py3.8.egg/aiohttp/connector.py", line 858, in _create_connection
                                             _, proto = await self._create_direct_connection(
                                           File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.6.2-py3.8.egg/aiohttp/connector.py", line 980, in _create_direct_connecti>
                                             transp, proto = await self._wrap_create_connection(
                                           File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.6.2-py3.8.egg/aiohttp/connector.py", line 936, in _wrap_create_connection
                                             return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
                                           File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
                                             sock = await self._connect_sock(
                                           File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
                                             await self.sock_connect(sock, address)
                                           File "/usr/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
                                             return await fut
                                         asyncio.exceptions.CancelledError

                                         During handling of the above exception, another exception occurred:

                                         Traceback (most recent call last):
                                           File "/usr/local/lib/python3.8/dist-packages/aiohttp-3.6.2-py3.8.egg/aiohttp/client.py", line 480, in _request
                                             conn = await self._connector.connect(
                                           File "/usr/local/lib/python3.8/dist-packages/async_timeout-3.0.1-py3.8.egg/async_timeout/__init__.py", line 45, in __exit__
                                             self._do_exit(exc_type)
                                           File "/usr/local/lib/python3.8/dist-packages/async_timeout-3.0.1-py3.8.egg/async_timeout/__init__.py", line 92, in _do_exit
                                             raise asyncio.TimeoutError
                                         asyncio.exceptions.TimeoutError

Do you know where is it ? 

Thank you,

Dov

**Comment by dovrose** [comment]
The new update to opt folder solved the issue
