### ISSUE TITLE
Discovery crashing

### ISSUE THREAD

**Issue by stefaanbolle** [deiger/AirCon#67]
After git pull to 0.3.5 by git pull and rerunning install. 
The discovery command gives below error
sudo python3 -m aircon discovery fglair-eu account password

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/openhabian/AirCon/aircon/__main__.py", line 31, in <module>
    from .aircon import Device
  File "/home/openhabian/AirCon/aircon/aircon.py", line 20, in <module>
    class Device(object):
  File "/home/openhabian/AirCon/aircon/aircon.py", line 22, in Device
    _FGL_DEVICES = re.compile(r'AP-W[ACDF]\dE')
NameError: name 're' is not defined
```

**Comment by deiger** [comment]
That was fast... It's fixed now.

**Comment by stefaanbolle** [comment]
Still an issue with the command

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/openhabian/AirCon/aircon/__main__.py", line 31, in <module>
    from .aircon import Device
  File "/home/openhabian/AirCon/aircon/aircon.py", line 21, in <module>
    class Device(object):
  File "/home/openhabian/AirCon/aircon/aircon.py", line 58, in Device
    def create(cls, config: Dict[str, str], notifier: Callable[[None], None]) -> Device:
NameError: name 'Device' is not defined
```

**Comment by stefaanbolle** [comment]
Discovery runs fine again, thanks!
The command to control the unit still gives the same error.
I now use one hisense.service to control 4 units with 1 http port (8889)

sudo curl -ik 'http://localhost:8889/hisense/command?device_ip=192.168.1.38&property=t_work_mode&value=HEAT' 
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
Content-Length: 55
Date: Wed, 13 Jan 2021 14:13:32 GMT
Server: Python/3.7 aiohttp/3.6.2
Connection: close

500 Internal Server Error

Server got itself in trouble%
```

**Comment by stefaanbolle** [comment]
Issue is closed, will continue to report above problem in #58
