### ISSUE TITLE
HA discovery issue

### ISSUE THREAD

**Issue by rotem925** [deiger/AirCon#68]
Hi @deiger 
In the latest version(docker), there is an issue with HA discovery configuration I guess.

They ACs are not discovered, and I can see the following error log in HA logs:
`
Exception in async_discover when dispatching 'mqtt_discovery_new_climate_mqtt': ({'name': 'Liv AC', 'unique_id': '405ee161114a', 'device': {'identifiers': ['hisense_ac_405ee161114a'], 'manufacturer': 'Hisense (tornado-us)', 'model': 'Smart-1-110', 'name': 'Liv AC', 'sw_version': 'HET 1.4.3 hisense ameba 2018-06-25 09:04:00 1.1.612'}, 'availability': [{'topic': 'hisense_ac/LWT'}, {'topic': 'hisense_ac/405ee161114a/available/status'}], 'precision': 1.0, 'temperature_unit': 'F', 'current_temperature_topic': 'hisense_ac/405ee161114a/f_temp_in/status', 'fan_mode_command_topic': 'hisense_ac/405ee161114a/t_fan_speed/command', 'fan_mode_state_topic': 'hisense_ac/405ee161114a/t_fan_speed/status', 'fan_modes': ['auto', 'lower', 'low', 'medium', 'high', 'higher'], 'mode_command_topic': 'hisense_ac/405ee161114a/t_work_mode/command', 'mode_state_topic': 'hisense_ac/405ee161114a/t_work_mode/status', 'modes': ['off', 'fan_only', 'heat', 'cool', 'dry', 'auto'], 'power_command_topic': 'hisense_ac/405ee161114a/t_power/command', 'power_state_topic': 'hisense_ac/405ee161114a/t_power/status', 'swing_mode_command_topic': 'hisense_ac/405ee161114a/t_fan_power/command', 'swing_mode_state_topic': 'hisense_ac/405ee161114a/t_fan_power/status', 'swing_modes': ['on', 'off'], 'temperature_command_topic': 'hisense_ac/405ee161114a/t_temp/command', 'temperature_state_topic': 'hisense_ac/405ee161114a/t_temp/status', 'max_temp': ['86'], 'min_temp': ['61'], 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/climate.py", line 257, in async_discover config = PLATFORM_SCHEMA(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: expected float for dictionary value @ data['max_temp']`

This error log is for all ACs I have. None of them are discovered.

**Comment by rotem925** [comment]
Just checked...
Not sure that's the correct way, but:
if you change the max_temp and min_temp to be floats and not strings, it is working as expected.

**Comment by rotem925** [comment]
OK, my previous suggestion is not entirely correct.
I was not able to set the temp above 2c after this change.
It just fixed the discovery..

**Comment by rotem925** [comment]
So, this is what I needed to modify (did it inside the container)

```
        config['max_temp'] = 86 if device.is_fahrenheit else 30,
        config['min_temp'] = 61 if device.is_fahrenheit else 16,
```
Somehow it had -14 for min temp, and +2 for max temp when looking at HA.
So I had to remove from the MQTT the climate configuration topic completely in order to let HA to pick the correct value again.
