### ISSUE TITLE
HomeAssistant AEH-W4E1 - AC found but no command&control

### ISSUE THREAD

**Issue by suppolo83** [deiger/AirCon#73]
Hello,

I suppose I followed the instruction properly but my HA found the two AC splits (AEH-W4E1) with no status feedback or command possibility. This is the log, any idea?

await self._perform_request(session, config)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 79, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
  File "/app/aircon/notifier.py", line 114, in _perform_request
    async with session.request(method, url, json=self._json, headers=config.headers) as resp:
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
E0117 23:53:49.402  notifier.py:87] [KeepAlive] Failed to send local_reg keep alive to the AC.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/app/aircon/__main__.py", line 250, in run
    query_status_worker(devices), notifier.start(session))
  File "/app/aircon/__main__.py", line 150, in setup_and_run_http_server
    await site.start()
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1389, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 1883): address already in use
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/aircon/notifier.py", line 84, in start
    await self._perform_request(session, config)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 79, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
  File "/app/aircon/notifier.py", line 114, in _perform_request
    async with session.request(method, url, json=self._json, headers=config.headers) as resp:
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
E0117 23:53:49.406  notifier.py:87] [KeepAlive] Failed to send local_reg keep alive to the AC.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/app/aircon/__main__.py", line 250, in run
    query_status_worker(devices), notifier.start(session))
  File "/app/aircon/__main__.py", line 150, in setup_and_run_http_server
    await site.start()
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1389, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 1883): address already in use
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/aircon/notifier.py", line 84, in start
    await self._perform_request(session, config)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 79, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
  File "/app/aircon/notifier.py", line 114, in _perform_request
    async with session.request(method, url, json=self._json, headers=config.headers) as resp:
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed

**Comment by deiger** [comment]
The `error while attempting to bind on address ('0.0.0.0', 1883)` is strange. From a brief search it seems that it might have to do with running two MQTT brokers at once. Please check.

**Comment by byxil** [comment]
Try to set mqtt port to 8888, for me this work, other mqtt use 1883 port

**Comment by dab-17** [comment]
Hi, i've the same problem.
I'm using dokcer with mosquitto and aircon.
I tried to delete old xx_config.jso, then i switched mosquitto on the port 8888, but now I receive "connection refused" error in the aircon container logs.
Some ideas?
Thanks
