### ISSUE TITLE
HomeAssistant add-on found Aeh-W4b1 but  not available

### ISSUE THREAD

**Issue by tatluigi** [deiger/AirCon#75]
return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
  File "/app/aircon/notifier.py", line 114, in _perform_request
    async with session.request(method, url, json=self._json, headers=config.headers) as resp:
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
D0121 08:15:51.330  notifier.py:113] [KeepAlive] Sending POST http://192.168.0.9/local_reg.json {"local_reg": {"ip": "192.168.0.30", "notify": 1, "port": 1883, "uri": "/local_lan"}}
E0121 08:15:51.333  notifier.py:87] [KeepAlive] Failed to send local_reg keep alive to the AC.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/app/aircon/__main__.py", line 250, in run
    query_status_worker(devices), notifier.start(session))
  File "/app/aircon/__main__.py", line 150, in setup_and_run_http_server
    await site.start()
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1389, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 1883): address already in use
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/aircon/notifier.py", line 84, in start
    await self._perform_request(session, config)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 79, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
  File "/app/aircon/notifier.py", line 114, in _perform_request
    async with session.request(method, url, json=self._json, headers=config.headers) as resp:
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
D0121 08:15:51.439  notifier.py:113] [KeepAlive] Sending POST http://192.168.0.9/local_reg.json {"local_reg": {"ip": "192.168.0.30", "notify": 1, "port": 1883, "uri": "/local_lan"}}
E0121 08:15:51.440  notifier.py:87] [KeepAlive] Failed to send local_reg keep alive to the AC.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/app/aircon/__main__.py", line 250, in run
    query_status_worker(devices), notifier.start(session))
  File "/app/aircon/__main__.py", line 150, in setup_and_run_http_server
    await site.start()
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1389, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 1883): address already in use
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/aircon/notifier.py", line 84, in start
    await self._perform_request(session, config)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 79, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 42, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/tenacity-6.3.1-py3.7.egg/tenacity/_asyncio.py", line 45, in __call__
    result = await fn(*args, **kwargs)
  File "/app/aircon/notifier.py", line 114, in _perform_request
    async with session.request(method, url, json=self._json, headers=config.headers) as resp:
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp-3.6.2-py3.7.egg/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed

MQTT discovery data:
Topic: homeassistant/climate/28ede03b271f/hvac/config
Payload
Subscribed topics:
hisense_ac/LWT
6 messaggi ricevuti più di recente
Received 7:53:20
QoS: 0, Retained
Payload: offline
Received 7:53:57
QoS: 0
Payload: online
Received 8:05:17
QoS: 0
Payload: offline
Received 8:05:21
QoS: 0
Payload: online
Received 8:14:47
QoS: 0
Payload: offline
Received 8:14:52
QoS: 0
Payload: online
hisense_ac/28ede03b271f/available/status
10 messaggi ricevuti più di recente
Received 8:18:59
QoS: 0
Payload: offline
Received 8:18:59
QoS: 0
Payload: offline
Received 8:18:59
QoS: 0
Payload: offline
Received 8:18:59
QoS: 0
Payload: offline
Received 8:18:59
QoS: 0
Payload: offline
Received 8:18:59
QoS: 0
Payload: offline
Received 8:19:00
QoS: 0
Payload: offline
Received 8:19:00
QoS: 0
Payload: offline
Received 8:19:00
QoS: 0
Payload: offline
Received 8:19:00
QoS: 0
Payload: offline

**Comment by deiger** [comment]
Could you please detail your config file?

**Comment by deiger** [comment]
The `error while attempting to bind on address ('0.0.0.0', 1883)` is strange. From a brief search it seems that it might have to do with running two MQTT brokers at once. Please check.

**Comment by tatluigi** [comment]
Hi deiger
I had mistakenly set the mqtt port (1883)
now setting port 8888 seems to be fine
actual config:
app:
  - username: **********
    password: **********
    code: oem-eu
log_level: DEBUG
mqtt_host: localhost
mqtt_user: *****
mqtt_pass: ******
port: 8888

**Comment by gtrizzo** [comment]
> Hi deiger
> I had mistakenly set the mqtt port (1883)
> now setting port 8888 seems to be fine
> actual config:
> app:
> 
> * username: **********
>   password: **********
>   code: oem-eu
>   log_level: DEBUG
>   mqtt_host: localhost
>   mqtt_user: *****
>   mqtt_pass: ******
>   port: 8888

Hi, thanks for the tip, I have 2 hisense AC with the Aeh-W4b1 but only one is recognized ... Do you know how to recognize them all?

Thanks for your help

**Comment by gtrizzo** [comment]
Hi,

Delete the Aircon file configuration on HA under Config\hisense and restart
Aircon service, in my case It worked.

Il gio 8 apr 2021, 19:45 wifi75 ***@***.***> ha scritto:
