### ISSUE TITLE
Unable to discover devices.

### ISSUE THREAD

**Issue by akhtar321h** [deiger/AirCon#80]
Hi,
I am using this module with fglair app.
but when I am running discovery command getting error: `E0204 13:03:06.411  discovery.py:43] Failed to login to Hisense server: Status 401: Unauthorized.`
Please let me know what is the issue
i am running this command:
`python3.7 -m aircon discovey fglair-eu foo@example.com my_pass`

**Comment by deiger** [comment]
Is [this](https://play.google.com/store/apps/details?id=com.fujitsu.fglair) the app?
This error means that the authentication failed. In the app it does work?

**Comment by akhtar321h** [comment]
Now it's working if i am passing this command:
`python3.7 -m aircon discovey fglair-us foo@example.com my_pass`
I am getting response:
`E0204 16:08:05.449 discovery.py:71] No device is configured! Please configure a device first.`
Right now no device is registered in my app.
Is this correct response?

**Comment by deiger** [comment]
Yes. You need to first configure the A/C in the app, once. Then the discovery will be able to fetch the encryption key from Ayla Network's server, and use it to communicated with the A/C locally.

**Comment by akhtar321h** [comment]
Hi, my devices are discovered and the result is:
```
root@dell-Embedded-Box-PC-3000:~/raw/AirCon-master# python3.7 -m aircon discovery fglair-us abc@gmail.com mypass
Device AC000W00XXXXXXX has:
                              IP address: 192.168.2.29
                              lanip_key: j1d61nYCYUiQAHbGydFgy9LWaLzwxx==
                              lanip_key_id: 25820


Device AC000W00YYYYYYY has:
                              IP address: 192.168.2.18
                              lanip_key: FHQsGzSSQdXqcTy0Ef3WjblVBTYYYY==
                              lanip_key_id: 37440
```
After this what i need to do, I am not getting anything.
While executing this command:
`python3.7 -m aircon run --port 8888 --config config.json --mqtt_host localhost`
Getting error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/raw/AirCon-master/aircon/__main__.py", line 301, in <module>
    asyncio.run(run(parsed_args))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/root/raw/AirCon-master/aircon/__main__.py", line 186, in run
    mqtt_client.connect(parsed_args.mqtt_host, parsed_args.mqtt_port)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```
Please help me with this.

**Comment by roxyamaha** [comment]
@akhtar321h did you manage to solve this error?
