### ISSUE TITLE
TypeError: 'bool' object is not callable upon startup

### ISSUE THREAD

**Issue by madecto** [deiger/AirCon#93]
Hello and thanks for your efforts,
I'm trying to run your component as a standalone service on a Pi4 with a selfinstalled HomeAssistant. Mosquitto is running and credentials are good.
I've just updated to the latest git, ran setup from the `homeassistant` user in the VENV, discovered my 3 AC units as per your instructions and tried running one of the servers to check on the HA integration.
The service appears to launch, announces itself on MQTT (and thus HA sees it for a brief moment) and then goes _seppuku_:

```(homeassistant) homeassistant@koku:~$ python -m aircon run -p 10003 --config config_smallbedroomac.json --mqtt_host localhost --mqtt_user hisense:_redacted_ --mqtt_topic hisense_ac_smallbedroom
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/srv/homeassistant/lib/python3.7/site-packages/aircon-0.3.9-py3.7.egg/aircon/__main__.py", line 304, in <module>
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/srv/homeassistant/lib/python3.7/site-packages/aircon-0.3.9-py3.7.egg/aircon/__main__.py", line 253, in run
  File "/srv/homeassistant/lib/python3.7/site-packages/aircon-0.3.9-py3.7.egg/aircon/__main__.py", line 159, in mqtt_loop
  File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/srv/homeassistant/lib/python3.7/site-packages/paho/mqtt/client.py", line 3030, in _handle_connack
    self, self._userdata, flags_dict, result)
  File "/srv/homeassistant/lib/python3.7/site-packages/aircon-0.3.9-py3.7.egg/aircon/mqtt_client.py", line 29, in mqtt_on_connect
TypeError: 'bool' object is not callable
```

Any idea of what I might be missing?

Thanks in advance,
Giulio

**Comment by yedidiaklein** [comment]
Fixed it.

edit aircon/mqtt_client.py
and change on line 29
      if device.available():
to
      if device.available:
